### Consulta de Clasificacion de Gastos
GET http://localhost:3000/api/metadata/clasificacion_gasto
Content-Type: application/json
Authorization: Basic {{$dotenv API_USER}} {{$dotenv API_PASSWORD}}


### Consulta de Clasificacion de Gastos
GET http://localhost:3000/api/metadata/metadatos_operaciones
Content-Type: application/json
Authorization: Basic {{$dotenv API_USER}} {{$dotenv API_PASSWORD}}